server:
  port: 8001

spring:
  profiles:
    active: dev  #走dev 配置文件中的环境
  datasource:
    #    type: com.alibaba.druid.pool.DruidDataSource  #引入自定义的阿里云数据源
    #    type: com.zaxxer.hikari.HikariDataSource     #指定数据源的类型HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/monitor?characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000     #等待连接池分配链接的最大时长（毫秒），超过这个时长断开？
      minimum-idle: 5               #最小连接数
      maximum-pool-size: 20         #最大连接数
      auto-commit: true             #自动提交
      idle-timeout: 600000          #连接超时的最大时长（豪秒），超时则被释放
      pool-name: DataSourceHikariCP #连接池名字
      max-lifetime: 1800000         #连接的生命时长（毫秒），超时而且没被使用则被释放
      connection-test-query: SELECT 1
  banner:
    location: banner/fozu.txt
    #  mvc:
    #    static-path-pattern: /haha/**
    #  访问URL路径：http://localhost:8001/haha/3.jpg， 访问的是static 目录下的3.jpg 图片，/haha/** 定义的是路由前缀，
    #  http://localhost:8001/  默认访问的是static 目录下单 index.html 文件

    #  mvc:
    #    static-path-pattern: /static/**
    #静态资源文件配置，默认是 static 目录

  #模版
  thymeleaf:
    prefix: classpath:/templates/html/
    suffix: .html

  web:
    resources:
      static-locations:
        [ classpath:/haha/ ]
  #限制上传文件大小
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 2MB

  # 配置日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai



# mybatis 相关的配置
mybatis:
  type-aliases-package: com.yksj.entity #所有数据库表逆向后--映射后的实体类【entity/pojo/Bean】
  mapper-locations: classpath:mapper/*.xml #所有mapper映射的文件所在的目录位置
  #configuration:
  # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启mybatis的日志实现，可以在控制台打印输出SQL语句日志 ，生成环境要去掉，否则日志非常大
#通用mapper配置
mapper:
  mappers: com.yksj.monitor.my.mapper.MyMapper  #所有mapper都需要实现的接口
  not-empty: false #在进行数据库操作的时候，判断一个属性是否为空的时候，是否需要自动追加不为空字符串的判断
  # 例如 userName!=null 后面不需要 userName!=""
  identity: MYSQL  #身份标识

#分页插件助手的配置
pagehelper:
  support-methods-arguments: true
  helper-dialect: mysql #方言


#自动义配置
self:
  custom:
    config:
      sdkSecret: 123
      host: https://www.baidu.com
      port: ${server.port}

