server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/monitor?characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
  banner:
    location: banner/fozu.txt
    #  mvc:
    #    static-path-pattern: /haha/**
    #  访问URL路径：http://localhost:8001/haha/3.jpg， 访问的是static 目录下的3.jpg 图片，/haha/** 定义的是路由前缀，
    #  http://localhost:8001/  默认访问的是static 目录下单 index.html 文件

    #  mvc:
    #    static-path-pattern: /static/**

    #静态资源文件配置，默认是 static 目录
  web:
    resources:
      static-locations:
        [ classpath:/haha/ ]
  #限制上传文件大小
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 2MB

  # 配置日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai



# mybatis 相关的配置
mybatis:
  type-aliases-package: com.yksj.entity #所有数据库表逆向后--映射后的实体类【entity/pojo/Bean】
  mapper-locations: classpath:mapper/*.xml #所有mapper映射的文件所在的目录位置
#通用mapper配置
mapper:
  mappers: com.yksj.monitor.my.mapper.MyMapper  #所有mapper都需要实现的接口
  not-empty: false #在进行数据库操作的时候，判断一个属性是否为空的时候，是否需要自动追加不为空字符串的判断
                   # 例如 userName!=null 后面不需要 userName!=""
  identity: MYSQL  #身份标识

#分页插件助手的配置
pagehelper:
  support-methods-arguments: true
  helper-dialect: mysql #方言


#自动义配置
self:
  custom:
    config:
      sdkSecret: 123
      host: https://www.baidu.com
      port: ${server.port}

